-- 添加子论坛
insert into boards
    (board_name)
    values
    ('分享'),
    ('问答'),
    ('文学'),
    ('艺术'),
    ('社会'),
    ('计算机'),
    ('人文'),
    ('动物世界'),
    ('花花草草');

-- 添加测试数据
insert into topic
    (title, board_id, article, topic_image_path, post_man, board_name)
    values
    ('分享子论坛', 1, '分享子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '分享'),
    ('分享子论坛', 1, '分享子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '分享'),
    ('分享子论坛', 1, '分享子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '分享'),
    ('分享子论坛', 1, '分享子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '分享'),
    ('分享子论坛', 1, '分享子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '分享'),
    ('分享子论坛', 1, '分享子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '分享'),
    ('分享子论坛', 1, '分享子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '分享'),
    ('分享子论坛', 1, '分享子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '分享'),
    ('分享子论坛', 1, '分享子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '分享'),
    ('分享子论坛', 1, '分享子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '分享'),
    ('分享子论坛', 1, '分享子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '分享'),
    ('分享子论坛', 1, '分享子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '分享'),
    ('分享子论坛', 1, '分享子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '分享'),
    ('分享子论坛', 1, '分享子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '分享'),
    ('分享子论坛', 1, '分享子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '分享'),
    ('分享子论坛', 1, '分享子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '分享'),
    ('分享子论坛', 1, '分享子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '分享'),
    ('分享子论坛', 1, '分享子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '分享'),
    ('分享子论坛', 1, '分享子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '分享'),
    ('分享子论坛', 1, '分享子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '分享'),
    ('分享子论坛', 1, '分享子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '分享'),
    ('分享子论坛', 1, '分享子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '分享'),
    ('分享子论坛', 1, '分享子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '分享'),
    ('分享子论坛', 1, '分享子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '分享'),
    ('分享子论坛', 1, '分享子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '分享'),
    ('分享子论坛', 1, '分享子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '分享'),
    ('分享子论坛', 1, '分享子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '分享'),
    ('分享子论坛', 1, '分享子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '分享'),
    ('分享子论坛', 1, '分享子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '分享'),
    ('分享子论坛', 1, '分享子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '分享');

insert into topic
    (title, board_id, article, topic_image_path, post_man, board_name)
    values
    ('问答子论坛', 2, '问答子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '问答'),
    ('问答子论坛', 2, '问答子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '问答'),
    ('问答子论坛', 2, '问答子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '问答'),
    ('问答子论坛', 2, '问答子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '问答'),
    ('问答子论坛', 2, '问答子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '问答'),
    ('问答子论坛', 2, '问答子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '问答'),
    ('问答子论坛', 2, '问答子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '问答'),
    ('问答子论坛', 2, '问答子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '问答'),
    ('问答子论坛', 2, '问答子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '问答'),
    ('问答子论坛', 2, '问答子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '问答'),
    ('问答子论坛', 2, '问答子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '问答'),
    ('问答子论坛', 2, '问答子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '问答'),
    ('问答子论坛', 2, '问答子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '问答'),
    ('问答子论坛', 2, '问答子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '问答'),
    ('问答子论坛', 2, '问答子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '问答'),
    ('问答子论坛', 2, '问答子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '问答'),
    ('问答子论坛', 2, '问答子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '问答'),
    ('问答子论坛', 2, '问答子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '问答'),
    ('问答子论坛', 2, '问答子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '问答'),
    ('问答子论坛', 2, '问答子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '问答'),
    ('问答子论坛', 2, '问答子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '问答'),
    ('问答子论坛', 2, '问答子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '问答'),
    ('问答子论坛', 2, '问答子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '问答'),
    ('问答子论坛', 2, '问答子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '问答'),
    ('问答子论坛', 2, '问答子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '问答'),
    ('问答子论坛', 2, '问答子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '问答'),
    ('问答子论坛', 2, '问答子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '问答'),
    ('问答子论坛', 2, '问答子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '问答'),
    ('问答子论坛', 2, '问答子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '问答'),
    ('问答子论坛', 2, '问答子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '问答');

insert into topic
    (title, board_id, article, topic_image_path, post_man, board_name)
    values
    ('文学子论坛', 3, '文学子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '文学'),
    ('文学子论坛', 3, '文学子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '文学'),
    ('文学子论坛', 3, '文学子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '文学'),
    ('文学子论坛', 3, '文学子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '文学'),
    ('文学子论坛', 3, '文学子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '文学'),
    ('文学子论坛', 3, '文学子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '文学'),
    ('文学子论坛', 3, '文学子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '文学'),
    ('文学子论坛', 3, '文学子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '文学'),
    ('文学子论坛', 3, '文学子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '文学'),
    ('文学子论坛', 3, '文学子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '文学'),
    ('文学子论坛', 3, '文学子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '文学'),
    ('文学子论坛', 3, '文学子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '文学'),
    ('文学子论坛', 3, '文学子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '文学'),
    ('文学子论坛', 3, '文学子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '文学'),
    ('文学子论坛', 3, '文学子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '文学'),
    ('文学子论坛', 3, '文学子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '文学'),
    ('文学子论坛', 3, '文学子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '文学'),
    ('文学子论坛', 3, '文学子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '文学'),
    ('文学子论坛', 3, '文学子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '文学'),
    ('文学子论坛', 3, '文学子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '文学'),
    ('文学子论坛', 3, '文学子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '文学'),
    ('文学子论坛', 3, '文学子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '文学'),
    ('文学子论坛', 3, '文学子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '文学'),
    ('文学子论坛', 3, '文学子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '文学'),
    ('文学子论坛', 3, '文学子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '文学'),
    ('文学子论坛', 3, '文学子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '文学'),
    ('文学子论坛', 3, '文学子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '文学'),
    ('文学子论坛', 3, '文学子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '文学'),
    ('文学子论坛', 3, '文学子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '文学'),
    ('文学子论坛', 3, '文学子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '文学');

insert into topic
    (title, board_id, article, topic_image_path, post_man, board_name)
    values
    ('艺术子论坛', 4, '艺术子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '艺术'),
    ('艺术子论坛', 4, '艺术子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '艺术'),
    ('艺术子论坛', 4, '艺术子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '艺术'),
    ('艺术子论坛', 4, '艺术子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '艺术'),
    ('艺术子论坛', 4, '艺术子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '艺术'),
    ('艺术子论坛', 4, '艺术子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '艺术'),
    ('艺术子论坛', 4, '艺术子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '艺术'),
    ('艺术子论坛', 4, '艺术子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '艺术'),
    ('艺术子论坛', 4, '艺术子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '艺术'),
    ('艺术子论坛', 4, '艺术子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '艺术'),
    ('艺术子论坛', 4, '艺术子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '艺术'),
    ('艺术子论坛', 4, '艺术子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '艺术'),
    ('艺术子论坛', 4, '艺术子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '艺术'),
    ('艺术子论坛', 4, '艺术子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '艺术'),
    ('艺术子论坛', 4, '艺术子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '艺术'),
    ('艺术子论坛', 4, '艺术子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '艺术'),
    ('艺术子论坛', 4, '艺术子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '艺术'),
    ('艺术子论坛', 4, '艺术子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '艺术'),
    ('艺术子论坛', 4, '艺术子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '艺术'),
    ('艺术子论坛', 4, '艺术子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '艺术'),
    ('艺术子论坛', 4, '艺术子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '艺术'),
    ('艺术子论坛', 4, '艺术子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '艺术'),
    ('艺术子论坛', 4, '艺术子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '艺术'),
    ('艺术子论坛', 4, '艺术子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '艺术'),
    ('艺术子论坛', 4, '艺术子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '艺术'),
    ('艺术子论坛', 4, '艺术子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '艺术'),
    ('艺术子论坛', 4, '艺术子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '艺术'),
    ('艺术子论坛', 4, '艺术子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '艺术'),
    ('艺术子论坛', 4, '艺术子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '艺术'),
    ('艺术子论坛', 4, '艺术子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '艺术');

insert into topic
    (title, board_id, article, topic_image_path, post_man, board_name)
    values
    ('社会子论坛', 5, '社会子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '社会'),
    ('社会子论坛', 5, '社会子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '社会'),
    ('社会子论坛', 5, '社会子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '社会'),
    ('社会子论坛', 5, '社会子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '社会'),
    ('社会子论坛', 5, '社会子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '社会'),
    ('社会子论坛', 5, '社会子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '社会'),
    ('社会子论坛', 5, '社会子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '社会'),
    ('社会子论坛', 5, '社会子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '社会'),
    ('社会子论坛', 5, '社会子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '社会'),
    ('社会子论坛', 5, '社会子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '社会'),
    ('社会子论坛', 5, '社会子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '社会'),
    ('社会子论坛', 5, '社会子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '社会'),
    ('社会子论坛', 5, '社会子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '社会'),
    ('社会子论坛', 5, '社会子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '社会'),
    ('社会子论坛', 5, '社会子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '社会'),
    ('社会子论坛', 5, '社会子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '社会'),
    ('社会子论坛', 5, '社会子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '社会'),
    ('社会子论坛', 5, '社会子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '社会'),
    ('社会子论坛', 5, '社会子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '社会'),
    ('社会子论坛', 5, '社会子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '社会'),
    ('社会子论坛', 5, '社会子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '社会'),
    ('社会子论坛', 5, '社会子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '社会'),
    ('社会子论坛', 5, '社会子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '社会'),
    ('社会子论坛', 5, '社会子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '社会'),
    ('社会子论坛', 5, '社会子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '社会'),
    ('社会子论坛', 5, '社会子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '社会'),
    ('社会子论坛', 5, '社会子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '社会'),
    ('社会子论坛', 5, '社会子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '社会'),
    ('社会子论坛', 5, '社会子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '社会'),
    ('社会子论坛', 5, '社会子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '社会');

insert into topic
    (title, board_id, article, topic_image_path, post_man, board_name)
    values
    ('计算机子论坛', 6, '计算机子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '计算机'),
    ('计算机子论坛', 6, '计算机子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '计算机'),
    ('计算机子论坛', 6, '计算机子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '计算机'),
    ('计算机子论坛', 6, '计算机子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '计算机'),
    ('计算机子论坛', 6, '计算机子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '计算机'),
    ('计算机子论坛', 6, '计算机子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '计算机'),
    ('计算机子论坛', 6, '计算机子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '计算机'),
    ('计算机子论坛', 6, '计算机子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '计算机'),
    ('计算机子论坛', 6, '计算机子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '计算机'),
    ('计算机子论坛', 6, '计算机子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '计算机'),
    ('计算机子论坛', 6, '计算机子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '计算机'),
    ('计算机子论坛', 6, '计算机子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '计算机'),
    ('计算机子论坛', 6, '计算机子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '计算机'),
    ('计算机子论坛', 6, '计算机子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '计算机'),
    ('计算机子论坛', 6, '计算机子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '计算机'),
    ('计算机子论坛', 6, '计算机子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '计算机'),
    ('计算机子论坛', 6, '计算机子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '计算机'),
    ('计算机子论坛', 6, '计算机子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '计算机'),
    ('计算机子论坛', 6, '计算机子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '计算机'),
    ('计算机子论坛', 6, '计算机子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '计算机'),
    ('计算机子论坛', 6, '计算机子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '计算机'),
    ('计算机子论坛', 6, '计算机子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '计算机'),
    ('计算机子论坛', 6, '计算机子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '计算机'),
    ('计算机子论坛', 6, '计算机子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '计算机'),
    ('计算机子论坛', 6, '计算机子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '计算机'),
    ('计算机子论坛', 6, '计算机子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '计算机'),
    ('计算机子论坛', 6, '计算机子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '计算机'),
    ('计算机子论坛', 6, '计算机子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '计算机'),
    ('计算机子论坛', 6, '计算机子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '计算机'),
    ('计算机子论坛', 6, '计算机子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '计算机');

insert into topic
    (title, board_id, article, topic_image_path, post_man, board_name)
    values
    ('人文子论坛', 7, '人文子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '人文'),
    ('人文子论坛', 7, '人文子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '人文'),
    ('人文子论坛', 7, '人文子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '人文'),
    ('人文子论坛', 7, '人文子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '人文'),
    ('人文子论坛', 7, '人文子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '人文'),
    ('人文子论坛', 7, '人文子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '人文'),
    ('人文子论坛', 7, '人文子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '人文'),
    ('人文子论坛', 7, '人文子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '人文'),
    ('人文子论坛', 7, '人文子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '人文'),
    ('人文子论坛', 7, '人文子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '人文'),
    ('人文子论坛', 7, '人文子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '人文'),
    ('人文子论坛', 7, '人文子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '人文'),
    ('人文子论坛', 7, '人文子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '人文'),
    ('人文子论坛', 7, '人文子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '人文'),
    ('人文子论坛', 7, '人文子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '人文'),
    ('人文子论坛', 7, '人文子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '人文'),
    ('人文子论坛', 7, '人文子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '人文'),
    ('人文子论坛', 7, '人文子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '人文'),
    ('人文子论坛', 7, '人文子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '人文'),
    ('人文子论坛', 7, '人文子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '人文'),
    ('人文子论坛', 7, '人文子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '人文'),
    ('人文子论坛', 7, '人文子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '人文'),
    ('人文子论坛', 7, '人文子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '人文'),
    ('人文子论坛', 7, '人文子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '人文'),
    ('人文子论坛', 7, '人文子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '人文'),
    ('人文子论坛', 7, '人文子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '人文'),
    ('人文子论坛', 7, '人文子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '人文'),
    ('人文子论坛', 7, '人文子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '人文'),
    ('人文子论坛', 7, '人文子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '人文'),
    ('人文子论坛', 7, '人文子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '人文');

insert into topic
    (title, board_id, article, topic_image_path, post_man, board_name)
    values
    ('动物世界子论坛', 8, '动物世界子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '动物世界'),
    ('动物世界子论坛', 8, '动物世界子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '动物世界'),
    ('动物世界子论坛', 8, '动物世界子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '动物世界'),
    ('动物世界子论坛', 8, '动物世界子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '动物世界'),
    ('动物世界子论坛', 8, '动物世界子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '动物世界'),
    ('动物世界子论坛', 8, '动物世界子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '动物世界'),
    ('动物世界子论坛', 8, '动物世界子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '动物世界'),
    ('动物世界子论坛', 8, '动物世界子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '动物世界'),
    ('动物世界子论坛', 8, '动物世界子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '动物世界'),
    ('动物世界子论坛', 8, '动物世界子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '动物世界'),
    ('动物世界子论坛', 8, '动物世界子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '动物世界'),
    ('动物世界子论坛', 8, '动物世界子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '动物世界'),
    ('动物世界子论坛', 8, '动物世界子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '动物世界'),
    ('动物世界子论坛', 8, '动物世界子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '动物世界'),
    ('动物世界子论坛', 8, '动物世界子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '动物世界'),
    ('动物世界子论坛', 8, '动物世界子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '动物世界'),
    ('动物世界子论坛', 8, '动物世界子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '动物世界'),
    ('动物世界子论坛', 8, '动物世界子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '动物世界'),
    ('动物世界子论坛', 8, '动物世界子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '动物世界'),
    ('动物世界子论坛', 8, '动物世界子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '动物世界'),
    ('动物世界子论坛', 8, '动物世界子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '动物世界'),
    ('动物世界子论坛', 8, '动物世界子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '动物世界'),
    ('动物世界子论坛', 8, '动物世界子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '动物世界'),
    ('动物世界子论坛', 8, '动物世界子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '动物世界'),
    ('动物世界子论坛', 8, '动物世界子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '动物世界'),
    ('动物世界子论坛', 8, '动物世界子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '动物世界'),
    ('动物世界子论坛', 8, '动物世界子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '动物世界'),
    ('动物世界子论坛', 8, '动物世界子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '动物世界'),
    ('动物世界子论坛', 8, '动物世界子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '动物世界'),
    ('动物世界子论坛', 8, '动物世界子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '动物世界');

insert into topic
    (title, board_id, article, topic_image_path, post_man, board_name)
    values
    ('花花草草子论坛', 9, '花花草草子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '花花草草'),
    ('花花草草子论坛', 9, '花花草草子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '花花草草'),
    ('花花草草子论坛', 9, '花花草草子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '花花草草'),
    ('花花草草子论坛', 9, '花花草草子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '花花草草'),
    ('花花草草子论坛', 9, '花花草草子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '花花草草'),
    ('花花草草子论坛', 9, '花花草草子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '花花草草'),
    ('花花草草子论坛', 9, '花花草草子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '花花草草'),
    ('花花草草子论坛', 9, '花花草草子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '花花草草'),
    ('花花草草子论坛', 9, '花花草草子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '花花草草'),
    ('花花草草子论坛', 9, '花花草草子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '花花草草'),
    ('花花草草子论坛', 9, '花花草草子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '花花草草'),
    ('花花草草子论坛', 9, '花花草草子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '花花草草'),
    ('花花草草子论坛', 9, '花花草草子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '花花草草'),
    ('花花草草子论坛', 9, '花花草草子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '花花草草'),
    ('花花草草子论坛', 9, '花花草草子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '花花草草'),
    ('花花草草子论坛', 9, '花花草草子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '花花草草'),
    ('花花草草子论坛', 9, '花花草草子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '花花草草'),
    ('花花草草子论坛', 9, '花花草草子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '花花草草'),
    ('花花草草子论坛', 9, '花花草草子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '花花草草'),
    ('花花草草子论坛', 9, '花花草草子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '花花草草'),
    ('花花草草子论坛', 9, '花花草草子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '花花草草'),
    ('花花草草子论坛', 9, '花花草草子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '花花草草'),
    ('花花草草子论坛', 9, '花花草草子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '花花草草'),
    ('花花草草子论坛', 9, '花花草草子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '花花草草'),
    ('花花草草子论坛', 9, '花花草草子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '花花草草'),
    ('花花草草子论坛', 9, '花花草草子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '花花草草'),
    ('花花草草子论坛', 9, '花花草草子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '花花草草'),
    ('花花草草子论坛', 9, '花花草草子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '花花草草'),
    ('花花草草子论坛', 9, '花花草草子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '花花草草'),
    ('花花草草子论坛', 9, '花花草草子论坛测试数据', 'public/uploads/default.jpeg', 'admin', '花花草草');

insert into user
    (username, email, password, register_time, login_time)
    values
    ('admin', 'admin@qq.com', 'abc123', '2019-3-29', '2019-3-29');
